// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCC5aHOCt0i7llxnFtRQzxxXZSEabZshoY',
    appId: '1:714687087598:web:16b73e9e69b7e683d284ff',
    messagingSenderId: '714687087598',
    projectId: 'fyp-navigator-app',
    authDomain: 'fyp-navigator-app.firebaseapp.com',
    storageBucket: 'fyp-navigator-app.appspot.com',
    measurementId: 'G-QMY24FHYYR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMODGqImbMxestKxSnNE7jFbIiuQ_lpvA',
    appId: '1:714687087598:android:5815def281fe9956d284ff',
    messagingSenderId: '714687087598',
    projectId: 'fyp-navigator-app',
    storageBucket: 'fyp-navigator-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCevHrDqmZlPbJa_e5CULuAInm3gkaBlHk',
    appId: '1:714687087598:ios:a5a44c483a60fcdcd284ff',
    messagingSenderId: '714687087598',
    projectId: 'fyp-navigator-app',
    storageBucket: 'fyp-navigator-app.appspot.com',
    iosBundleId: 'com.example.finalYearProjectsNavigator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCevHrDqmZlPbJa_e5CULuAInm3gkaBlHk',
    appId: '1:714687087598:ios:a5a44c483a60fcdcd284ff',
    messagingSenderId: '714687087598',
    projectId: 'fyp-navigator-app',
    storageBucket: 'fyp-navigator-app.appspot.com',
    iosBundleId: 'com.example.finalYearProjectsNavigator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCC5aHOCt0i7llxnFtRQzxxXZSEabZshoY',
    appId: '1:714687087598:web:8d122fb86d0af51bd284ff',
    messagingSenderId: '714687087598',
    projectId: 'fyp-navigator-app',
    authDomain: 'fyp-navigator-app.firebaseapp.com',
    storageBucket: 'fyp-navigator-app.appspot.com',
    measurementId: 'G-SZESNPRSYM',
  );

}